# Create a dictionary where keys are full names and values are corresponding information
staff_data = {
    "Abdiyev Xasan Ergash o‘g‘li": "Information for Abdiyev Xasan Ergash o‘g‘li.",
    "Bekmetov Inomjon O'ktam o'gli": "Information for Bekmetov Inomjon O'ktam o'gli.",
    "Салямов Артур Рафаильевич": "Information for Салямов Артур Рафаильевич.",
    "Davronov Quvonchbek Komil o'g'li": "Information for Davronov Quvonchbek Komil o'g'li.",
    "Xoshimov Abbosxo'ja Akbarxo'ja o'g'li": "Information for Xoshimov Abbosxo'ja Akbarxo'ja o'g'li.",
    "Rustamov Akmal Suxrobovich": "Information for Rustamov Akmal Suxrobovich.",
    "Pulatov Bakhtiyor Alimovich": "Information for Pulatov Bakhtiyor Alimovich.",
    "Shodmonov Ruslan G‘olib o‘g‘li": "Information for Shodmonov Ruslan G‘olib o‘g‘li.",
    "Imomov Jamshidkhon Odilovich": "Information for Imomov Jamshidkhon Odilovich.",
    "Toxirjonov Nosirjon Toxirjon o'g'li": "Information for Toxirjonov Nosirjon Toxirjon o'g'li.",
    "Muhammadiyev Yusuf Yaxshiboyevich": "Information for Muhammadiyev Yusuf Yaxshiboyevich.",
    "Odambayev Asadbek Oybek o'g'li": "Information for Odambayev Asadbek Oybek o'g'li.",
    "Ismoilov Dustmurod G’aybulla o’g’li": "Information for Ismoilov Dustmurod G’aybulla o’g’li.",
    "Jasurbek Ibrohimov Ikromjon O'g'li": "Information for Jasurbek Ibrohimov Ikromjon O'g'li.",
    "Saidov Sanjar Raximjon o'g'li": "Information for Saidov Sanjar Raximjon o'g'li.",
    "Islombek Abdixakimov Bahodir o'g'li": "Information for Islombek Abdixakimov Bahodir o'g'li.",
    "Xojibayev Shoxrux Bekmurzayevich": "Information for Xojibayev Shoxrux Bekmurzayevich.",
    "To‘qliyev Abdirauf Bahodir o'g'li": "Information for To‘qliyev Abdirauf Bahodir o'g'li.",
    "Ergashev Shohjahon Erkin o‘g‘li": "Information for Ergashev Shohjahon Erkin o‘g‘li.",
    "Siddiqov Bahrom": "Information for Siddiqov Bahrom.",
    "Abduraxmonov Isoq Abduraim o'g'li": "Information for Abduraxmonov Isoq Abduraim o'g'li.",
    "Эргашов Достон Раджабович": "Information for Эргашов Достон Раджабович.",
    "Ğofurova San'atxon Akmaljon qizi": "Information for Ğofurova San'atxon Akmaljon qizi.",
    "Murtazayev Nasirulloxon Lutfulloxon o'g'li": "Information for Murtazayev Nasirulloxon Lutfulloxon o'g'li.",
    "Xudoyberdiyeva Dinora Zayniddin qizi": "Information for Xudoyberdiyeva Dinora Zayniddin qizi.",
    "ABDULXAMIDOV SARDOR ABDUJABBOR O'G'LI": "Information for ABDULXAMIDOV SARDOR ABDUJABBOR O'G'LI.",
    "Xulasova Kamola Nazirqul qizi": "Information for Xulasova Kamola Nazirqul qizi.",
    "Zakiryayev Jamshidbek Saminjon o'g'li": "Information for Zakiryayev Jamshidbek Saminjon o'g'li.",
    "Salimov Suhrobjon Sobirovich": "Information for Salimov Suhrobjon Sobirovich.",
    "Ro`zimurodov O`lmas Farxodovich": "Information for Ro`zimurodov O`lmas Farxodovich.",
    "Ayubjonov Rustamjon Akmalovich": "Information for Ayubjonov Rustamjon Akmalovich.",
    "Sultonov Baxodir Saloxidin o'g'li": "Information for Sultonov Baxodir Saloxidin o'g'li.",
    "Suhrobbek Allaberganov G'ayrat o'g'li": "Information for Suhrobbek Allaberganov G'ayrat o'g'li.",
    "Baxtiyorov Munavvar Asil o'g'li": "Information for Baxtiyorov Munavvar Asil o'g'li.",
    "Olishboyev Salohiddin Abdukarim o'g'li": "Information for Olishboyev Salohiddin Abdukarim o'g'li.",
    "Sultanov Shoxjaxon Rahmon o'g'li": "Information for Sultanov Shoxjaxon Rahmon o'g'li.",
    "Qonarbaev David Xalbaevich": "Information for Qonarbaev David Xalbaevich.",
    "Madraximov Muxammad Shuxrat o'g'li": "Information for Madraximov Muxammad Shuxrat o'g'li.",
    "Xo'jamberdiyev Shaxzod Shuhrat o'g'li": "Information for Xo'jamberdiyev Shaxzod Shuhrat o'g'li.",
    "Lutfiddinov Ziyodxon Bekzodbek o'g'li": "Information for Lutfiddinov Ziyodxon Bekzodbek o'g'li.",
    "Muradov Farxat Muxmudjanovich": "Information for Muradov Farxat Muxmudjanovich.",
    "Berdiqulov Ixtiyor Faxriddin o'g'li":"asdasd",
    "Maxmudov A’zamjon Talatovich": "afasdfsd",
    "Abdiyev Xasan Ergash o'g'li" : 'asdasd',
    "Mustafoyeva Madina Sherbek qizi":'adadasd',
    "Abdulxamidov Sardor Adbujabbor o'g'li":"adasdas",
    "Valijonov Baxtiyor Baxodirjon o'g'li":"asdsa",
    "Pardaev Sardor Farxod o`g`li":"askdjfasdf",
    "Abdug`afforov Abdulaziz Alisher o`g`li":'1asdfsdf',
    "Abduhoshimjonov Ahmadjon Arabjon o‘g‘li":"1asdfa",
    "Shernazarov Temurbek To'lqin o'g'li":"afasfdas",
    "Sultanov Shoxjaxon Rahmon o'g'li":"1ascjyh",
    "Toshbvoyev Nurbek O'tkir o'g'li":"13efr",
    "Mo'minjon Ismatillo o'g'li Tursunov":"asdfas",
    "Davlatjon Ilhomov Umidjon O'g'li":"1asdgfew",
    "Sabirov Ruslan Azizovich":"131",
    "Toshboyev Nurbek O'tkir o'g'li": "Information for Toshboyev Nurbek O'tkir o'g'li.",
    "Karimov Nuriddin Maxamadjonovich": "Information for Karimov Nuriddin Maxamadjonovich.",
    "Jalgasov Denis Kenes ugli": "Information for Jalgasov Denis Kenes ugli.",
    "Sabirov Ruslan Azizovich": "Information for Sabirov Ruslan Azizovich.",
    "Dexkonov Nurmuxammad Dumebekovich": "Information for Dexkonov Nurmuxammad Dumebekovich.",
    "Yo’ldasheva Mavludaxon Kamoljon qizi": "Information for Yo’ldasheva Mavludaxon Kamoljon qizi.",
    "Yakubova Maftunaxon Kozimjon qizi": "Information for Yakubova Maftunaxon Kozimjon qizi.",
    "Oralbaev Karim Genjebay uli": "Information for Oralbaev Karim Genjebay uli.",
    "Mirzaabdullayev Boyir Sodikov Humoyun": "Information for Mirzaabdullayev Boyir Sodikov Humoyun.",
    "Isaboyev Omadbek Ergashboyevich": "Information for Isaboyev Omadbek Ergashboyevich.",
    "Manopov Bexzodbek Zapardinovich": "Information for Manopov Bexzodbek Zapardinovich.",
    "Yakubov Makhmudbek Navro'bek o'g'li": "Information for Yakubov Makhmudbek Navro'bek o'g'li.",
    "ISMIOLOVA GULNORA SAMANDAROVNA": "Information for ISMIOLOVA GULNORA SAMANDAROVNA.",
    "Махамматумарова Наргиза Мансурбек қизи": "Information for Махамматумарова Наргиза Мансурбек қизи.",
    "Shahzod Yovqochev": "Information for Shahzod Yovqochev.",
    "Matazimov Muhammadjon Toxirjon o'g'li": "Information for Matazimov Muhammadjon Toxirjon o'g'li.",
    "Tojimurodov Bekmurod Dilmurodjon o' g' li": "Information for Tojimurodov Bekmurod Dilmurodjon o' g' li.",
    "Mamadaliyev Adxamjon Komilovich": "Information for Mamadaliyev Adxamjon Komilovich.",
    "Raxmatov Jahongir Xolmatjonovich": "Information for Raxmatov Jahongir Xolmatjonovich.",
    "Oxunov Abdurahim Iminjonovich": "Information for Oxunov Abdurahim Iminjonovich.",
    "Rustambekov Sanjarbek O'tkirbek o'g'li": "Information for Rustambekov Sanjarbek O'tkirbek o'g'li.",
    "Begmatov Sanjarbek Akimjonovich": "Information for Begmatov Sanjarbek Akimjonovich.",
    "Boqiyev Abdujolol Abdulxamitovich": "Information for Boqiyev Abdujolol Abdulxamitovich.",
    "Atamuratov Aziz Rustamovich": "Information for Atamuratov Aziz Rustamovich.",
    "Nasimov J.A.": "Information for Nasimov J.A.",
    "Hoshimov Sardorbek Sobir o‘g‘li": "Information for Hoshimov Sardorbek Sobir o‘g‘li.",
    "Qosimov Akmal Mirboboevich": "Information for Qosimov Akmal Mirboboevich.",
    "Yodgorov Farrux Toxirovich": "Information for Yodgorov Farrux Toxirovich.",
    "Yodgorov Farrux Toxirovich": "Information for Yodgorov Farrux Toxirovich.",
    "Toshboyev Nurbek O‘tkir o‘g‘li": "Information for Toshboyev Nurbek O‘tkir o‘g‘li.",
    "Primqulova Gulrux Juraqobilovna": "Information for Primqulova Gulrux Juraqobilovna.",
    "Toshboyev Nurbek O‘tkir o‘g‘li": "Information for Toshboyev Nurbek O‘tkir o‘g‘li.",
    "Jurayev Tulkin Arzikulovich": "Information for Jurayev Tulkin Arzikulovich.",
    "Kurbanov Faxriddin Bazarboyevich": "Information for Kurbanov Faxriddin Bazarboyevich.",
    "Ollanazarov Sultannazar Jumanazarovich": "Information for Ollanazarov Sultannazar Jumanazarovich.",
    "Xudoynazarov Egambergan Madraximovich": "Information for Xudoynazarov Egambergan Madraximovich.",
    "Rashidov Obidjon Fayzullayevich": "Information for Rashidov Obidjon Fayzullayevich.",
    "Usmonaliyev Bexzod Alijon o‘g‘li": "Information for Usmonaliyev Bexzod Alijon o‘g‘li.",
    "Nabiyev Azamat Shodiyevich": "Information for Nabiyev Azamat Shodiyevich.",
    "Fayzillayev Zohid Bahodirovich": "Information for Fayzillayev Zohid Bahodirovich.",
    "Allanazarova Ziyada Shamshetovna": "Information for Allanazarova Ziyada Shamshetovna.",
    "Kamolov Shokir Obidovich": "Information for Kamolov Shokir Obidovich.",
    "Muzaffarov Sarvar Sanjar o'g'li": "Information for Muzaffarov Sarvar Sanjar o'g'li.",
    "Toshboyev Nurbek O‘tkir o‘g‘li": "Information for Toshboyev Nurbek O‘tkir o‘g‘li.",
    "Abdiyev Xasan Ergash o‘g‘li": "Information for Abdiyev Xasan Ergash o‘g‘li.",
    "Xoldorov Otabek Doniyor o'g'li": "Information for Xoldorov Otabek Doniyor o'g'li.",
    "Abdashimova Xumora Abrorxo'ja qizi": "Information for Abdashimova Xumora Abrorxo'ja qizi.",
    "Abdukadirova Kamila Baxadirovna": "Information for Abdukadirova Kamila Baxadirovna.",
    "Musurmanov Nurbek Ummatqul o‘g‘li": "Information for Musurmanov Nurbek Ummatqul o‘g‘li.",
    "Xolmuratov Shaxriddin Baxriddinovich": "Information for Xolmuratov Shaxriddin Baxriddinovich",
    "Mo‘minov Jasur": "Information for Mo‘minov Jasur.",
    "Alijonov Jasurbek Rustambek o‘g‘li": "Information for Alijonov Jasurbek Rustambek o‘g‘li.",
    "Otabek Xoldorov Donyor O'g'li": "Information for Otabek Xoldorov Donyor O'g'li.",
    "Xudoynazarov Muxriddin Shuhrat o'g'li": "Information for Xudoynazarov Muxriddin Shuhrat o'g'li.",
    "Toshboyev Nurbek O‘tkir o‘g‘li": "Information for Toshboyev Nurbek O‘tkir o‘g‘li.",
    "Tursunov Shohzod": "Information for Tursunov Shohzod.",
    "Malikov Umid Muratovich": "Information for Malikov Umid Muratovich.",
    "Abdusattorova Charos Abdulaziz qizi": "Information for Abdusattorova Charos Abdulaziz qizi.",
    "Ablaberdiev Laziz": "Information for Ablaberdiev Laziz.",
    "Toshboyev Nurbek O'tkir o‘g‘li": "Information for Toshboyev Nurbek O'tkir o‘g‘li.",
    "Toshtemirov Akmaljon To'lqinjon o‘g‘li": "Information for Toshtemirov Akmaljon To'lqinjon o‘g‘li.",
    "Mo‘minov Shavkatjon Abdushukurovich": "Information for Mo‘minov Shavkatjon Abdushukurovich.",
    "Lyusikov Аrtemiy Аleksandrovich": "Information for Lyusikov Аrtemiy Аleksandrovich.",
    "Ko‘palova Muxlisa Rustam qizi": "Information for Ko‘palova Muxlisa Rustam qizi.",
    "Qurbonov Rahmatullo To‘ymuhamad o‘g‘li": "Information for Qurbonov Rahmatullo To‘ymuhamad o‘g‘li.",
    "Soliyeva Fotima Farhod qizi": "Information for Soliyeva Fotima Farhod qizi.",
    "Nishonov Kamoliddin Axrorjon o‘g‘li": "Information for Nishonov Kamoliddin Axrorjon o‘g‘li.",
    "Turdiqulova Jannatxon Shavkat qizi": "Information for Turdiqulova Jannatxon Shavkat qizi."
}









def getInfo(name):
    if name in staff_data:
        return staff_data[name]
    else:
        return "Ism Topilmadi , Iltimos Royxatdan Xatosiz ko'chirib oling !"




# list1 = list(staff_data)
# def only_Keys():
#     for a in list1:
#         print(a)


